# GNU makefile

get_x3dom = x3dom.js x3dom.css

# Because Firefox and Chromium browsers consider X3D file in a directory
# above the file path directory to be cross domain, we copy models to
# example directories.  I.E. we can't use <inline url="../model.x3d"/> on
# the local machine without a http server.  We need all files to exist in
# the example directory or any level of sub-directory of that directory.

CFLAGS = -g -Werror

cbins = clickWindow printPointer

clickWindow_LDFLAGS = -lX11 -lXtst
printPointer_LDFLAGS = -lX11

copies =\
 045_xx_intervalAnimate/gnome.x3d\
 055_min_fullscreen/gnome.x3d\
 060_x_fullscreen/gnome.x3d\
 069_xx_fullscreen/gnome.x3d

build: $(get_x3dom) $(copies) firefoxProfile $(cbins)

# make a hard link from top directory to example directory
# ln $(patsubst $(dir $@)%,%,$@) $@
# Or
# make a copy of it with a This is a copy file header
#
# A sym link will not work.
$(copies):
	echo "<!-- This is a copy of ../$(patsubst $(dir $@)%,%,$@)" > $@
	echo "  Do not edit this file -->" >> $@
	cat $(patsubst $(dir $@)%,%,$@) >> $@

$(cbins): %: %.o
	$(CC) $(CFLAGS) $($@_CFLAGS) -o $@ $^ $($@_LDFLAGS)

%.o: %.c
	$(CC) $(CFLAGS) $($@_CFLAGS) -c -o $@ $<

$(get_x3dom):
	wget http://examples.x3dom.org/example/$@ -O $@

firefoxProfile:
	./mk_firefoxProfile.bash x3domVR_tutorial $(PWD)/$@

clean:
	rm -f $(copies) $(cbins) *.o
	rm -rf firefoxProfile

# Do not remove files we had to download unless we want a cleaner clean
cleaner distclean: clean
	rm -f $(get_x3dom)
